[package]
name = "payable-demo"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/spacekit-xyz/spacekit-core"
homepage = "https://github.com/spacekit-xyz/spacekit-core/tree/main/sdks/spacekit-standard-library/payments/payable-demo"
[lib]
crate-type = ["cdylib"]

[dependencies]
spacekit-contract-sdk = { version = "0.1.0", path = "../../../spacekit-contract-sdk" }
wee_alloc = "0.4"
